In [1]:
from pycaret.classification import setup, compare_models, evaluate_model
import pandas as pd

In [2]:
# load treated data set
train_set = pd.read_parquet('../data/05_model_input/train_dataset_kobe_dev.parquet')
test_set = pd.read_parquet('../data/05_model_input/test_dataset_kobe_dev.parquet')
train_set.head()

,lat,lon,minutes_remaining,period,playoffs,shot_distance,shot_made_flag
26131,33.8633,-118.2818,8,3,0,18,1.0
16057,34.0443,-118.2698,9,3,0,0,1.0
1103,34.0443,-118.2698,6,3,0,0,0.0
26435,34.0443,-118.2698,5,2,1,0,1.0
21046,34.0433,-118.2748,3,1,0,0,1.0

In [3]:
# check if it has null values
train_set.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16228 entries, 26131 to 14158
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lat                16228 non-null  float64
 1   lon                16228 non-null  float64
 2   minutes_remaining  16228 non-null  int64
 3   period             16228 non-null  int64
 4   playoffs           16228 non-null  int64
 5   shot_distance      16228 non-null  int64
 6   shot_made_flag     16228 non-null  float64
dtypes: float64(3), int64(4)
memory usage: 1014.2 KB

In [4]:
# check basis statistics
train_set.describe()

,lat,lon,minutes_remaining,period,playoffs,shot_distance,shot_made_flag
count,16228.000000,16228.000000,16228.000000,16228.000000,16228.000000,16228.000000,16228.000000
mean,33.980860,-118.262196,5.100136,2.475228,0.149864,10.214013,0.477323
std,0.065865,0.093494,3.422079,1.149379,0.356949,7.554856,0.499501
min,33.809300,-118.487800,0.000000,1.000000,0.000000,0.000000,0.000000
25%,33.926300,-118.313800,2.000000,1.000000,0.000000,1.000000,0.000000
50%,33.999800,-118.269800,5.000000,3.000000,0.000000,12.000000,0.000000
75%,34.044300,-118.194800,8.000000,3.000000,0.000000,17.000000,1.000000
max,34.088300,-118.049800,11.000000,7.000000,1.000000,26.000000,1.000000

In [5]:
target_column = 'shot_made_flag'
s = setup(train_set, target = target_column, session_id=123, fix_imbalance=True)

In [6]:
# check inbalance 
train_set[target_column].value_counts()

shot_made_flag
0.0    8482
1.0    7746
Name: count, dtype: int64

In [7]:
best = compare_models()

Initiated  . . . . . . . . . . . . . . . . . .              19:54:38
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

In [8]:
# See performance of the model
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…